### ISSUE TITLE
docs(graphql*compodoc*github): add documentaion [WiP]

### ISSUE THREAD

**Issue by ivan-varabyou** [ivan-varabyou/angular-nx#17]
проговорить
- [x] links, what to see
- [ ] working with github
- [x] IDE customization
[webinar from developers ](https://www.youtube.com/watch?v=Ozt8pBq9Mys&list=WL&index=3&t=1s)
- [x] change scripts (backend => db)
## At this stage, You need to do following
- [x] add comments for graphql files
- [ ]  add generation documentation for applications
[settiong compodoc | Nx docs](https://nx.dev/latest/angular/guides/running-custom-commands#steps)
- [ ]  Solve the problem of multiple applications and README.md in the root of the repository
- [ ]  Settings scripts
- [ ]  Add documentation on github page
- [ ] Set-up an action for autogeneration of documentation
 

```
name: Generate documentation
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Copy branch [master]
        uses: actions/checkout@v2
      - 
        name: Install NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - 
        name: Install dependencies
        run: npm install      
      - 
        name: Run compodoc
        run: npx nx affected --all --target=compodoc    
      - 
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GH_PAGE }}
```
